# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [2]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [43]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [44]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [45]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [46]:
X = iris.data
y = iris.target

In [47]:
import pandas as pd

i = pd.DataFrame(X)

In [48]:
i.head(10)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
5  5.4  3.9  1.7  0.4
6  4.6  3.4  1.4  0.3
7  5.0  3.4  1.5  0.2
8  4.4  2.9  1.4  0.2
9  4.9  3.1  1.5  0.1

In [49]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [50]:
from sklearn.model_selection import  train_test_split

train_X,test_X,train_y,test_y = train_test_split(X,y,test_size = 0.25,random_state =5)

In [51]:
print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(112, 4)
(112,)
(38, 4)
(38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [52]:
import numpy as np

print(np.unique(test_y))
print(np.unique(train_y))

[0 1 2]
[0 1 2]


In [53]:
from keras.utils import to_categorical

test_y = to_categorical(test_y,num_classes=3)
train_y = to_categorical(train_y,num_classes=3)

In [54]:
test_y[:10]

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [55]:
train_y[:10]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [56]:
#Initialize Sequential Graph (model)

model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [57]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation="softmax"))

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [59]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [63]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


4 Inputs (petal length, petal width, sepal length, sepal width) will have 4 weights and 1 bias.

So for 3 outputs below are the equation for each neurons.


y1 = w1x1+w2x2+w3x3+w4x4+b1

y2 = w5x5+w6x6+w7x7+w8x8+b2

y3 = w9x9+w10x10+w11x11+w12x12+b3

Above there are 12 Weights(W) and 3 (Bias) so the triannable params is 15

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [64]:
model.fit(train_X, train_y, 
          validation_data=(test_X, test_y), 
          epochs=100,
          batch_size=32)

Epoch 1/100
4/4 [==============================] - 1s 79ms/step - loss: 2.9114 - accuracy: 0.3284 - val_loss: 1.8648 - val_accuracy: 0.3158
Epoch 2/100
4/4 [==============================] - 0s 15ms/step - loss: 1.6830 - accuracy: 0.3207 - val_loss: 1.4003 - val_accuracy: 0.1579
Epoch 3/100
4/4 [==============================] - 0s 14ms/step - loss: 1.3446 - accuracy: 0.1138 - val_loss: 1.2645 - val_accuracy: 0.1579
Epoch 4/100
4/4 [==============================] - 0s 15ms/step - loss: 1.2399 - accuracy: 0.2103 - val_loss: 1.2163 - val_accuracy: 0.1579
Epoch 5/100
4/4 [==============================] - 0s 15ms/step - loss: 1.1723 - accuracy: 0.1548 - val_loss: 1.1785 - val_accuracy: 0.2895
Epoch 6/100
4/4 [==============================] - 0s 16ms/step - loss: 1.1342 - accuracy: 0.2225 - val_loss: 1.1427 - val_accuracy: 0.2368
Epoch 7/100
4/4 [==============================] - 0s 15ms/step - loss: 1.0620 - accuracy: 0.2702 - val_loss: 1.1131 - val_accuracy: 0.2105
Epoch 8/100
4/4 [===

## Question 10

### Make predictions
- Predict labels on one row

In [69]:
model.predict(train_X[:1])

array([[0.8863714 , 0.06898785, 0.04464085]], dtype=float32)

**As per the above Prediction, We are seeing the first row belongs to Iris Setosa with the predict probality with 0.88%**

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [70]:
train_y[0:1]

array([[1., 0., 0.]], dtype=float32)

**The first row belongs to Iris Setosa as per actual labels, My model has predicted with 0.88% as Iris Setosa**

---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [71]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [72]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [73]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [75]:
# run this cell to upload file if you are using google colab
# from google.colab import files
# files.upload()

# Getting the prices.csv from Google Drive

In [74]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [136]:
import pandas as pd

house_price_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/prices.csv')

In [137]:
house_price_df.sample(10)

date symbol        open  ...         low        high      volume
602339  2015-01-07    TEL   61.599998  ...   61.320000   63.049999   1929000.0
391548  2013-04-23    WAT   89.449997  ...   89.230003   95.519997   1856800.0
277395  2012-05-07    EMR   48.520000  ...   48.509998   49.049999   3893300.0
684165  2015-09-03   CSCO   25.879999  ...   25.730000   26.150000  27958400.0
646426  2015-05-18    AZO  690.000000  ...  688.880005  695.500000    280600.0
651579  2015-06-02     LB   86.370003  ...   85.860001   86.889999   1172800.0
46165   2010-05-25    AMT   38.820000  ...   38.400002   39.680000   5042600.0
555785  2014-08-21    TSO   64.849998  ...   63.740002   64.849998   2495600.0
654555  2015-06-10   LRCX   82.550003  ...   82.019997   82.839996   1172400.0
15061   2010-02-18    NEE   45.849998  ...   45.570000   45.900002   2949000.0

[10 rows x 7 columns]

In [138]:
house_price_df.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [139]:
house_price_df.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

In [140]:
house_price_df.drop(columns=['date','symbol'],inplace=True)

In [141]:
house_price_df.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [142]:
house_price_1000_df = house_price_df.head(1000)

In [143]:
house_price_1000_df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [144]:
X = house_price_1000_df[['open','close','low','high']]

In [145]:
y = house_price_1000_df['volume']/1000000

In [146]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [147]:
X = np.asarray(X,dtype='float32')
y = np.asarray(y,dtype='float32')

In [148]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [149]:
X = tf.math.l2_normalize(X)

In [150]:
X

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.00799559, 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [151]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1,1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [152]:
def prediction(x,w,b):
  xw_matmul = tf.matmul(x,w)
  output = tf.add(xw_matmul,b)
  return output

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [153]:
def loss(y_actual,y_predicted):
  diff = y_actual -y_predicted
  square = tf.square(diff)
  loss = tf.reduce_mean(square)
  return loss

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [154]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
      t.watch([w,b])
        
      current_prediction = prediction(x, w, b)
      current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias - Gradient Descent
    w = w - (learning_rate*dw)
    b = b - (learning_rate*db)
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [155]:
# Train for 100 iterations

for i in range(100):
   w, b = train(X,y,w,b)
   print('Current Loss on iteration', i, 
          loss(y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16766
Current Loss on iteration 1 235.093
Current Loss on iteration 2 234.06105
Current Loss on iteration 3 233.06989
Current Loss on iteration 4 232.11801
Current Loss on iteration 5 231.20384
Current Loss on iteration 6 230.32588
Current Loss on iteration 7 229.48265
Current Loss on iteration 8 228.6729
Current Loss on iteration 9 227.89523
Current Loss on iteration 10 227.14842
Current Loss on iteration 11 226.4312
Current Loss on iteration 12 225.74228
Current Loss on iteration 13 225.08072
Current Loss on iteration 14 224.4454
Current Loss on iteration 15 223.83524
Current Loss on iteration 16 223.24925
Current Loss on iteration 17 222.68651
Current Loss on iteration 18 222.14604
Current Loss on iteration 19 221.62694
Current Loss on iteration 20 221.12845
Current Loss on iteration 21 220.64973
Current Loss on iteration 22 220.18993
Current Loss on iteration 23 219.7484
Current Loss on iteration 24 219.32436
Current Loss on iteration 25 218.91702
Cu

### Observe values of Weight
- Print the updated values

In [156]:
#Check Weights
print('Weights:\n', w.numpy())

Weights:
 [[0.0547828 ]
 [0.05488191]
 [0.05422734]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [157]:
print('Bias:\n',b.numpy())

Bias:
 [[4.607657]]
