# Lists, Dictionaries and Sets in Python

## Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [146]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [3]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


### Question 1
Adding to an existing list

Add 10 to list l1 given above

*Hint:  Use `append()`*

In [147]:
l1.append(10)
l1

['learning', 'Python', 'is fun?', True, 10]

### Question 2
Removing from an existing list

Remove 10 from l1

*Hint: use `remove()`*

In [148]:
l1.remove(10)
l1

['learning', 'Python', 'is fun?', True]

### Question 3
Join 2 lists l1 and l2

Hint: use **`+`** operator or **`extend()`**

In [16]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [149]:
l1.extend(l2)
l1

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]

### Question 4
Number List

Find Range and Mean of l3.

`l3 = [2,4,6,8]`

Hint: use **`len()`, `sum()`, `min()`, `max()`** functions
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [172]:
l3 = [2,4,6,8]

In [173]:
len(l3)

4

In [174]:
sum(l3)

20

In [175]:
min(l3)

2

In [176]:
max(l3)

8

In [177]:
import numpy as np
arr2 = np.array(l3)
arr2

array([2, 4, 6, 8])

In [178]:
arr2.mean()

5.0

In [179]:
arr2.size

4

### Question 5
Count the occurances of an element in a given list

Append the given sequence of numbers to l3 (given above)

0, 1, 3, 3, 5, 5, 7, 9

Count the occurences of 5 in l3.

Hint: use **`+`** operator to add multiple elements in the array and **`count()`** function to print the occurences

In [180]:
l3[4:] =[0, 1, 3, 3, 5, 5, 7, 9]

In [181]:
l3

[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

In [182]:
 l3.count(5)

2

### Question 6
Sorting and Reversing a list

sort and print l3 in ascending and descending order sequentially (given above)

Hint: use **`sort()`** function

In [183]:
l3.sort()   ##Ascending Order
l3

[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]

In [184]:
l3.sort(reverse= True)  ##Descending Order
l3

[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]

## Functions

**Example:**

**def** function_name(args)**:**

    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [185]:
def sum_3(x,y,z):
    return x+y+z

In [186]:
sum_3(10,10,10)

30

## Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [187]:
f =lambda x,y,z :x+y+z

f(10,10,10)

30

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns and operating on 2d matrices aren't readily available. So, we will use ***Numpy*** for such functions.



In [189]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [190]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Some functions on np.array()

In [191]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

Hint: You can also use **`np.identity()`** function

In [194]:

import numpy as np 
  
arr2d = np.identity(2, dtype = int) 

arr2d


array([[1, 0],
       [0, 1]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9, 8, 7, 6, 5, 4, 3, 2, 1 arranged in the same order

Use: **`np.matrix()`** function



In [193]:
arr2d_1 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])

arr2d_1.reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [77]:
np.matrix(data=[[9, 8, 7], [6, 5, 4], [3, 2, 1]])

matrix([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**

In [80]:
arr2d_1_reshape = arr2d_1.reshape(3,3)

arr2d_1_reshape

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [82]:
arr2d_1_reshape.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

### Question 4
Add (+) 1 to all the elements in the given matrix.

In [84]:
arr2d_sum = arr2d_1_reshape +1

In [85]:
arr2d_sum

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [86]:
arr2d_sub = arr2d_1_reshape -1
arr2d_sub

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [91]:
arr2d_mul = arr2d_1_reshape *2
arr2d_mul

array([[18, 16, 14],
       [12, 10,  8],
       [ 6,  4,  2]])

In [90]:
arr2d_div = arr2d_1_reshape /2
arr2d_div

array([[4.5, 4. , 3.5],
       [3. , 2.5, 2. ],
       [1.5, 1. , 0.5]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.

nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [95]:
nd6 = np.array([[ 1,4,9,121,144,169],[ 16,25,36,196,225,256],[ 49,64,81,289,324,361]])

nd6

array([[  1,   4,   9, 121, 144, 169],
       [ 16,  25,  36, 196, 225, 256],
       [ 49,  64,  81, 289, 324, 361]])

In [96]:
nd6.mean()

131.66666666666666

### Question 6

Find the dot product of two given matrices.

Hint: use **`np.dot()`**

In [103]:
arr_dot_1 = np.array([[1,2],[3,4]])

In [104]:
arr_dot_2 = np.array([[5,6],[7,8]])

In [106]:
arr_dot_1.dot(arr_dot_2)

array([[19, 22],
       [43, 50]])

# Pandas

We have seen Numpy in the last section. It is good at performing math operations on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](https://pandas.pydata.org/pandas-docs/stable/)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [0]:
import numpy as np
import pandas as pd

In [0]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

Hint: use **`.Series`**

In [110]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [116]:
import pandas as pd
df_1 = pd.Series(data = d1, index = ['a', 'b', 'c'])
df_1

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


Hint: use **`np.dot()`**

In [114]:
df_2 = pd.Series(data = {'a': 4, 'b': 5, 'c': 6}, index = ['a', 'b', 'c'])

df_2

a    4
b    5
c    6
dtype: int64

In [117]:
df_1.dot(df_2)

32

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [123]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [124]:
df1.iloc[1]

a    2
b    4
c    7
Name: 1, dtype: int64

### Question 4

Select column c in second row of df1.

Hint: For using labels use **`df.loc[row, column]`**

For using numeric indexed use **`df.iloc[]`**

For using mixture of numeric indexes and labels use **`df.ix[row, column]`**



In [126]:
df1['c']

0    6
1    7
2    8
Name: c, dtype: int64

## Using Dataframes on a dataset

### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors 


In [2]:
## Reading a dataset from a csv file using pandas.
import pandas as pd
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']
mtcars.head()

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


Hint: use **`type()`** and **`df.shape`**

In [136]:
mtcars.shape

(32, 12)

In [138]:
mtcars.dtypes

name     object
mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

Hint: use **`.head()`** and **`.tail()`**

In [139]:
mtcars.head(10)

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                      Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                  Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                    Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                    Merc 280  19.2    6  167.6  123  3.92  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2  
Valiant            20.22   1   0     3     1  
Duster 360         15.84   0   0     3     4  
Merc 240D          20.00   1   0     4     2  
Merc 230           22.90   1   0     4     2  
Merc 280           18.30   1   0     4     4

In [140]:
mtcars.tail(10)

name   mpg  cyl   disp   hp  drat     wt   qsec  \
name                                                                            
AMC Javelin            AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   
Camaro Z28              Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   
Fiat X1-9                Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   
Porsche 914-2        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   
Lotus Europa          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   
Ford Pantera L      Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   
Ferrari Dino          Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   
Maserati Bora        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   
Volvo 142E              Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   

                  vs  am  gear  carb  
name                                  
AMC Javelin        0   0     3     2  
Camaro Z28         0   0     3     4  
Pontiac Firebird   0   0     3     2  
Fiat X1-9          1   1     4     1  
Porsche 914-2      0   1     5     2  
Lotus Europa       1   1     5     2  
Ford Pantera L     0   1     5     4  
Ferrari Dino       0   1     5     6  
Maserati Bora      0   1     5     8  
Volvo 142E         1   1     4     2

### Question 7

Print all the column labels in the given dataset - mtcars.

Hint: use **`df.columns`**

In [141]:
mtcars.columns

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

Hint: **`mtcars.ix[:, :]`** gives all rows and columns in the dataset

In [3]:
mtcars.iloc[0:6,0:3]

name   mpg  cyl
name                                           
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6